"""SUDARSHAN — Laya System-1 Decision Planner.

Laya (NandhaKishorM/laya, Apache-2.0) is a fast, non-autoregressive System 1 decision
engine operating with calibrated probabilities over structured choices.

This planner queries either:
1. An in-process Laya agent (using `laya.load("convaiinnovations/laya-typed-decisions")`),
2. A self-hosted HTTP container running `laya-serve` on `/v1/systemone`, or
3. A deterministic mock provider for testing and offline CI.

BOUNDARY GUARANTEES:
- Laya ONLY selects actions from bounded candidate lists generated by ExplorationGraph.
- Laya NEVER generates raw shell/ADB commands.
- Laya NEVER determines BFCI, STEI, FRS, threat vectors, or malware verdicts.
"""

from __future__ import annotations

import asyncio
import logging
import os
import time
from typing import Any, Dict, List, Optional, Tuple

import httpx

from sudarshan_core.engines.agentic.agent_memory import AgentMemory
from sudarshan_core.engines.agentic.exploration_engine import ActionItem, ExplorationGraph
from sudarshan_core.engines.agentic.goal_tracker import GoalTracker
from sudarshan_core.engines.agentic.perception import Observation

logger = logging.getLogger("sudarshan.agentic.laya_planner")

DEFAULT_LAYA_ENDPOINT = os.getenv("SUDARSHAN_LAYA_URL", "http://127.0.0.1:8005/v1/systemone")
DEFAULT_LAYA_CHECKPOINT = os.getenv("SUDARSHAN_LAYA_MODEL", "convaiinnovations/laya-typed-decisions")
DEFAULT_LAYA_TIMEOUT = float(os.getenv("SUDARSHAN_LAYA_TIMEOUT_MS", "3000.0")) / 1000.0
DEFAULT_LAYA_CONFIDENCE_THRESHOLD = float(os.getenv("SUDARSHAN_LAYA_CONFIDENCE_THRESHOLD", "0.70"))
DEFAULT_LAYA_DEVICE = os.getenv("SUDARSHAN_LAYA_DEVICE", "auto")

# Global lazy cache for in-process Laya agent
_GLOBAL_LAYA_AGENT: Optional[Any] = None
_GLOBAL_LAYA_LOCK = asyncio.Lock() if hasattr(asyncio, "Lock") else None


class LayaPlanner:
    """Decision planner powered by the Laya System-1 calibrated decision engine."""

    def __init__(
        self,
        endpoint_url: Optional[str] = None,
        checkpoint: Optional[str] = None,
        api_key: str = "",
        device_serial: str = "",
        package_name: str = "",
        action_budget: int = 150,
        benchmark: Any = None,
        adb_path: str = "adb",
        exploration: Optional[ExplorationGraph] = None,
        timeout: float = DEFAULT_LAYA_TIMEOUT,
        confidence_threshold: float = DEFAULT_LAYA_CONFIDENCE_THRESHOLD,
        provider: Optional[str] = None,
        use_in_process: Optional[bool] = None,
    ) -> None:
        self.endpoint_url = endpoint_url or os.getenv("SUDARSHAN_LAYA_URL", DEFAULT_LAYA_ENDPOINT)
        self.checkpoint = checkpoint or os.getenv("SUDARSHAN_LAYA_MODEL", DEFAULT_LAYA_CHECKPOINT)
        self.api_key = api_key
        self.device_serial = device_serial
        self.package_name = package_name
        self.action_budget = action_budget
        self.benchmark = benchmark
        self.adb_path = adb_path
        self.exploration = exploration
        self.timeout = timeout
        self.confidence_threshold = confidence_threshold
        self.provider = provider or os.getenv("SUDARSHAN_LAYA_PROVIDER", "auto").lower()
        self.device = DEFAULT_LAYA_DEVICE

        if use_in_process is not None:
            self.use_in_process = use_in_process
        else:
            self.use_in_process = os.getenv("LAYA_MODE", "").lower() == "in_process"

        self._recent_screens: Dict[str, float] = {}
        logger.info(
            "[LayaPlanner] Initialized (checkpoint=%s, provider=%s, in_process=%s, endpoint=%s, device=%s)",
            self.checkpoint,
            self.provider,
            self.use_in_process,
            self.endpoint_url,
            self.device,
        )

    def invalidate_cache_for_screen(self, screen_hash: str) -> None:
        self._recent_screens.pop(screen_hash, None)

    async def decide(
        self,
        obs: Observation,
        memory: AgentMemory,
        goals: GoalTracker,
        *,
        deadline_seconds: Optional[float] = None,
    ) -> Optional[Dict[str, Any]]:
        """Evaluate candidate actions and select the highest-probability option."""
        if not self.exploration:
            logger.debug("[LayaPlanner] No exploration graph attached; skipping.")
            return None

        current_state_id = self.exploration._current_state_id
        if not current_state_id or current_state_id not in self.exploration.states:
            logger.debug("[LayaPlanner] Current state '%s' not in exploration graph.", current_state_id)
            return None

        state = self.exploration.states[current_state_id]
        unexplored = state.unexplored_actions()
        if not unexplored:
            logger.debug("[LayaPlanner] No unexplored actions in state '%s'.", current_state_id)
            return None

        candidates = [act for act in unexplored if not getattr(act, "failed", False)]
        if not candidates:
            logger.debug("[LayaPlanner] All unexplored actions in '%s' have previously failed.", current_state_id)
            return None

        # Build schema payload
        payload = self._serialize_candidates(obs, goals, candidates)

        t0 = time.monotonic()
        decision_resp: Optional[Dict[str, Any]] = None

        if self.provider == "mock":
            decision_resp = self._invoke_mock(obs, goals, candidates)
        elif self.use_in_process:
            decision_resp = await self._invoke_in_process(payload)
        else:
            # HTTP remote call to laya-serve
            call_timeout = self.timeout
            if deadline_seconds is not None:
                call_timeout = max(0.2, min(call_timeout, deadline_seconds - 0.1))
            decision_resp = await self._invoke_http(payload, call_timeout)

        latency = time.monotonic() - t0
        if not decision_resp:
            logger.warning("[LayaPlanner] Failed to retrieve decision (latency=%.3fs).", latency)
            return None

        selected_action = self._validate_and_deserialize(decision_resp, candidates)
        if selected_action and self.benchmark:
            try:
                self.benchmark.record_laya_decision(latency=latency, success=True)
            except Exception:
                pass

        return selected_action

    def _serialize_candidates(
        self,
        obs: Observation,
        goals: GoalTracker,
        candidates: List[ActionItem],
    ) -> Dict[str, Any]:
        """Format screen context and candidate options into Laya typed decision schema."""
        current_goal = goals.next_priority_goal()
        goal_text = f"Goal: {current_goal.name} - {current_goal.description}" if current_goal else "Goal: Explore application"

        state_text = (
            f"Screen: {obs.activity}\n"
            f"{goal_text}\n"
            f"Package: {self.package_name}\n"
            f"ScreenHash: {obs.screen_hash[:8] if obs.screen_hash else 'unknown'}"
        )

        criteria: Dict[str, str] = {}
        for act in candidates:
            label = act.label or "unlabeled"
            cls = act.class_name or "view"
            criteria[act.node_id] = f"{act.action_type.upper()} '{label}' (class: {cls})"

        return {
            "model": self.checkpoint,
            "state": state_text,
            "questions": {
                "action": {
                    "type": "choice",
                    "criteria": criteria,
                    "instructions": "Select the best action to advance the current investigation goal.",
                }
            },
        }

    async def _invoke_http(self, payload: Dict[str, Any], timeout: float) -> Optional[Dict[str, Any]]:
        """Dispatch HTTP request to laya-serve."""
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        try:
            async with httpx.AsyncClient(timeout=timeout) as client:
                resp = await client.post(self.endpoint_url, json=payload, headers=headers)
                resp.raise_for_status()
                return resp.json()
        except httpx.TimeoutException:
            logger.warning("[LayaPlanner] HTTP timeout after %.2fs at %s", timeout, self.endpoint_url)
            return None
        except httpx.HTTPStatusError as exc:
            logger.warning("[LayaPlanner] HTTP %d from %s: %s", exc.response.status_code, self.endpoint_url, exc.response.text[:200])
            return None
        except Exception as exc:
            logger.warning("[LayaPlanner] HTTP connection error: %s", exc)
            return None

    async def _invoke_in_process(self, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Run inference in-process using laya Agent."""
        global _GLOBAL_LAYA_AGENT
        try:
            if _GLOBAL_LAYA_AGENT is None:
                import laya
                # Run synchronous load in default threadpool
                loop = asyncio.get_running_loop()
                _GLOBAL_LAYA_AGENT = await loop.run_in_executor(
                    None, lambda: laya.load(self.checkpoint, device=self.device)
                )

            loop = asyncio.get_running_loop()
            res = await loop.run_in_executor(
                None,
                lambda: _GLOBAL_LAYA_AGENT.predict(
                    payload["state"],
                    payload["questions"],
                ),
            )
            return res
        except Exception as exc:
            logger.warning("[LayaPlanner] In-process inference error: %s", exc)
            return None

    def _invoke_mock(
        self,
        obs: Observation,
        goals: GoalTracker,
        candidates: List[ActionItem],
    ) -> Dict[str, Any]:
        """Deterministic mock provider for offline tests and simulation."""
        current_goal = goals.next_priority_goal()
        goal_name = current_goal.name.lower() if current_goal else ""

        # Priority 1: Match keyword in goal description
        for act in candidates:
            lbl = (act.label or "").lower()
            if any(token in lbl for token in ["login", "sign in", "submit", "next", "continue"]) and "login" in goal_name:
                return {"model": self.checkpoint, "answers": {"action": {"choice": act.node_id, "confidence": 0.95}}}

        # Priority 2: Input fields first
        inputs = [c for c in candidates if c.action_type in ("input", "type_text")]
        if inputs:
            return {"model": self.checkpoint, "answers": {"action": {"choice": inputs[0].node_id, "confidence": 0.90}}}

        # Fallback to first non-failed candidate
        return {"model": self.checkpoint, "answers": {"action": {"choice": candidates[0].node_id, "confidence": 0.85}}}

    def _validate_and_deserialize(
        self,
        response_json: Dict[str, Any],
        candidates: List[ActionItem],
    ) -> Optional[Dict[str, Any]]:
        """Validate response format, check confidence threshold, and construct canonical action."""
        answers = response_json.get("answers", {})
        action_ans = answers.get("action", {})
        chosen_id = action_ans.get("choice")
        confidence = float(action_ans.get("confidence", 1.0))

        if not chosen_id:
            logger.warning("[LayaPlanner] No choice returned in response: %s", response_json)
            return None

        if confidence < self.confidence_threshold:
            logger.info(
                "[LayaPlanner] Low confidence (%.3f < %.3f); rejecting choice '%s'",
                confidence,
                self.confidence_threshold,
                chosen_id,
            )
            return None

        # Verify chosen candidate exists
        matching = next((c for c in candidates if c.node_id == chosen_id), None)
        if not matching:
            logger.warning("[LayaPlanner] Hallucinated/invalid node_id '%s' not in candidates", chosen_id)
            return None

        action_dict: Dict[str, Any] = {
            "node_id": matching.node_id,
            "x": matching.center_x,
            "y": matching.center_y,
            "text": matching.label or "",
            "_action_id": matching.action_id,
            "_selected_by": "laya_planner",
            "_confidence": confidence,
            "reasoning": f"Laya System-1 choice: {matching.node_id} (conf={confidence:.2f})",
        }

        if matching.action_type in ("input", "type_text"):
            action_dict["tool"] = "type_text"
            if matching.field_kind:
                action_dict["field_hint"] = matching.field_kind
        elif matching.action_type in ("scroll", "swipe"):
            action_dict["tool"] = "scroll"
            action_dict["direction"] = getattr(matching, "direction", "down")
        else:
            action_dict["tool"] = "tap"

        return action_dict
