"""
SUDARSHAN - Synthetic Persona Generator
Deterministic test values that satisfy field constraints without using real secrets.
"""
from typing import Optional
from sudarshan_core.engines.agentic.field_taxonomy import FieldType

class SyntheticPersona:
    def __init__(self):
        self.values = {
            FieldType.PHONE: "9876543210",
            FieldType.MOBILE: "9876543210",
            FieldType.EMAIL: "test.user@sudarshan-analysis.test",
            FieldType.USERNAME: "sandbox_user",
            FieldType.USER_ID: "sandbox_id",
            FieldType.LOGIN_ID: "sandbox_id",
            FieldType.PASSWORD: "Test@123456",
            FieldType.PASSCODE: "123456",
            FieldType.PIN: "1234",
            FieldType.MPIN: "258036",
            FieldType.TPIN: "741852",
            FieldType.UPI_PIN: "369258",
            FieldType.ATM_PIN: "1472",
            FieldType.CARD_PIN: "1472",
            FieldType.OTP: "123456",
            FieldType.VERIFICATION_CODE: "123456",
            FieldType.AUTHENTICATION_CODE: "123456",
            FieldType.FIRST_NAME: "Rahul",
            FieldType.LAST_NAME: "Sharma",
            FieldType.FULL_NAME: "Rahul Sharma",
            FieldType.FATHER_NAME: "Amit Sharma",
            FieldType.MOTHER_NAME: "Sunita Sharma",
            FieldType.MOTHER_MAIDEN_NAME: "Sharma",
            FieldType.GUARDIAN_NAME: "Amit Sharma",
            FieldType.SPOUSE_NAME: "Priya Sharma",
            FieldType.DATE_OF_BIRTH: "01/01/2000",
            FieldType.AGE: "25",
            FieldType.DATE: "01/01/2026",
            FieldType.TIME: "10:00",
            FieldType.ADDRESS: "101 Sandbox Street, Cyber District",
            FieldType.ADDRESS_LINE_1: "101 Sandbox Street",
            FieldType.ADDRESS_LINE_2: "Cyber District",
            FieldType.HOUSE_NUMBER: "101",
            FieldType.FLAT_NUMBER: "101",
            FieldType.STREET: "Sandbox Street",
            FieldType.LANDMARK: "Near Security Lab",
            FieldType.CITY: "Pune",
            FieldType.STATE: "Maharashtra",
            FieldType.DISTRICT: "Pune",
            FieldType.COUNTRY: "India",
            FieldType.TALUKA: "Haveli",
            FieldType.TEHSIL: "Haveli",
            FieldType.PIN_CODE: "411001",
            FieldType.POSTAL_CODE: "411001",
            FieldType.ZIP_CODE: "411001",
            FieldType.PAN: "ABCDE1234F",
            FieldType.AADHAAR: "000000000000",
            FieldType.PASSPORT: "T0000000",
            FieldType.VOTER_ID: "ABC1234567",
            FieldType.DRIVING_LICENSE: "MH1200000000000",
            FieldType.BANK_NAME: "Test Bank",
            FieldType.ACCOUNT_NUMBER: "123456789012",
            FieldType.ACCOUNT_HOLDER_NAME: "Rahul Sharma",
            FieldType.IFSC: "TEST0000001",
            FieldType.BRANCH_CODE: "000001",
            FieldType.CARD_NUMBER: "4111111111111111",
            FieldType.CARD_HOLDER_NAME: "Rahul Sharma",
            FieldType.CARD_EXPIRY: "12/30",
            FieldType.CARD_CVV: "123",
            FieldType.UPI_ID: "sandbox@invalid",
            FieldType.VPA: "sandbox@invalid",
            FieldType.BENEFICIARY_NAME: "Test Beneficiary",
            FieldType.PAYEE: "Test Payee",
            FieldType.RECIPIENT: "Test Recipient",
            FieldType.MERCHANT: "Test Merchant",
            FieldType.AMOUNT: "10",
            FieldType.QUANTITY: "1",
            FieldType.SEARCH_QUERY: "test_query",
            FieldType.SEARCH: "test_query",
            FieldType.REFERRAL_CODE: "TESTPROMO",
            FieldType.PROMO_CODE: "TESTPROMO",
            FieldType.COUPON_CODE: "TESTPROMO",
            FieldType.COMPANY_NAME: "Test Organization",
            FieldType.EMPLOYEE_ID: "EMP12345",
            FieldType.STUDENT_ID: "STU12345",
            FieldType.ROLL_NUMBER: "12345",
            FieldType.REGISTRATION_NUMBER: "REG12345",
            FieldType.ORDER_ID: "ORD12345",
            FieldType.INVOICE_NUMBER: "INV12345",
            FieldType.REFERENCE_NUMBER: "REF12345",
            FieldType.TRANSACTION_ID: "TXN12345",
            FieldType.COMMENT: "Test comment",
            FieldType.DESCRIPTION: "Test description",
            FieldType.MESSAGE: "Test message",
            FieldType.NOTES: "Test notes",
            FieldType.UNKNOWN: "Test Input",
        }

    def get_value(self, field_type: FieldType) -> Optional[str]:
        return self.values.get(field_type, self.values[FieldType.UNKNOWN])

_global_persona = SyntheticPersona()

def generate_synthetic_value(field_type: FieldType) -> str:
    return _global_persona.get_value(field_type)
