graph TD
  STATE-001["LoginActivity (BANK_LOGIN) u:20"]
  STATE-002["LoginActivity (BANK_LOGIN) u:0"]
  STATE-003["LoginActivity (BANK_LOGIN) u:0"]
  STATE-004["FilePrefActivity (UNKNOWN) u:3"]
  STATE-005["FilePrefActivity (UNKNOWN) u:0"]
  STATE-006["LoginActivity (BANK_LOGIN) u:1"]
  STATE-007["LoginActivity (BANK_LOGIN) u:1"]
  STATE-008["SpaActivity (SYSTEM_PERMISSION) u:20"]
  STATE-009["SpaActivity (SYSTEM_PERMISSION) u:25"]
  STATE-010["SpaActivity (SYSTEM_PERMISSION) u:25"]
  STATE-001 -->|external_transition| EXT-001
  STATE-001 -->|click_text| EXT-001
  STATE-002 -->|type_text| STATE-002
  STATE-002 -->|type_text| STATE-002
  STATE-002 -->|click_text| STATE-003
  STATE-003 -->|click_text| STATE-004
  STATE-004 -->|type_text| STATE-004
  STATE-004 -->|type_text| STATE-004
  STATE-004 -->|click_text| STATE-005
  STATE-005 -->|click_text| STATE-004
  STATE-004 -->|click_text| STATE-005
  STATE-005 -->|click_text| STATE-002
  STATE-002 -->|click_text| STATE-002
  STATE-002 -->|click_text| STATE-006
  STATE-006 -->|click_text| STATE-002
  STATE-002 -->|type_text| STATE-007
  STATE-007 -->|click_text| STATE-007
  STATE-007 -->|click_text| STATE-007
  STATE-007 -->|click_text| STATE-008
  STATE-008 -->|external_transition| EXT-002
  STATE-008 -->|click_text| EXT-002
  STATE-008 -->|click_text| EXT-002
  STATE-008 -->|scroll| STATE-009
  STATE-009 -->|click_text| EXT-002
  STATE-009 -->|scroll| STATE-010
  STATE-010 -->|click_text| STATE-010
  EXT-003 -->|click_text| EXT-002
  EXT-003 -->|start_activity| STATE-002
  STATE-002 -->|press_back| STATE-002
  STATE-002 -->|press_back| EXT-003
  EXT-003 -->|click_text| EXT-002
  EXT-003 -->|click_text| EXT-002
  EXT-003 -->|start_activity| STATE-002
  STATE-002 -->|click_text| STATE-003
  STATE-003 -->|click_text| STATE-002
  STATE-002 -->|type_text| STATE-002
  STATE-002 -->|press_back| STATE-002
  STATE-002 -->|press_back| EXT-003
  EXT-003 -->|click_text| EXT-002
  EXT-003 -->|click_text| EXT-002